---

- hosts: all
  become: true
  pre_tasks: #se hacen antes de cualquier otra task
  
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
# ejemplo de cuando se tienen servidores con diferentes sistemas operativos 
# si hay varios os q usan apt (ej debian y ubuntu)
 #   when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages for ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: copy default html file for site 
    tags: apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package
      tags: ubuntu,mariadb,db
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"